pipeline {
  agent any

    tools {
        maven 'Maven'
        jdk 'JDK'
    }

  stages {
    stage('Build') {
      steps {
        echo "before build"
         bat '''
                cmd /c mvn -version
                cmd /c mvn clean package
                '''
        echo "after build"
      }
    }
    stage('SonarQube') {
      steps {
        echo "before sonar"
  bat '''
              'mvn sonar:sonar'
                '''
        
        echo "after sonar"
      }
    }
    stage('Docker Build') {
      steps {
  bat '''
              'docker build -t hello:latest -f docker/Dockerfile .'
                '''
       
      }
    }
    stage('Security Scan') {
      steps {
 bat '''
              'trivy image hello:latest'
                '''
      
      }
    }
    stage('Deploy') {
      steps {
 bat '''
                 'helm upgrade --install hello helm/hello-app'
                '''
    
      }
    }
  }
}