pipeline {
  agent any

    tools {
        maven 'Maven'
        jdk 'JDK'
    }
stages
{
 stage('Debug') {
    steps {
        sh '''
        uname -a
        which mvn || echo "Maven missing"
        java -version
        '''
    }
}
}
}